### PR TITLE
Redirect to blog url on button click

### LINKED ISSUE #169: Arrow Button in Blog Section not functional
**Describe the bug**
In the blog section card when the button is clicked the user should be redirected to the url provided in the card info, but this does not happen

**To Reproduce**
1. Run the project
2. Go to blogs section
3. Click on the arrow button

**Expected behavior**
As per intuition when the arrow button is clicked the user should be redirected to the blog url

**Is this responsiveness Issue**
NO

### PR DESCRIPTION
**Pull request by AkshayCHD**
Fixes #169

### CODE REVIEW

File: src/components/blogCard/BlogCard.js [hunk 1]
```diff
@@ -2,14 +2,21 @@ import React from "react";
...
+
   return (
     <div>
       <div class="blog-container">
         <a class="blog-card" href="#blog" >
           <h3 className="blog-title">{blog.title}</h3>
           <p class="small">{blog.description}</p>
           <div class="go-corner" >
-            <div class="go-arrow">→</div>
+            <div class="go-arrow" onClick={() => openUrlInNewTab(blog.url)}>→</div>
```
Comment (saadpasta) [inline src/components/blogCard/BlogCard.js:19]: Good Issue. Please add onClick Blog div, not on the arrow.

Comment (AkshayCHD) [reply src/components/blogCard/BlogCard.js]: @saadpasta Sure, Done

**Comment by kartik918** [comment]
I think @AkshayCHD has fixed quite a few bugs so I'm gonna give him the highest honor I can bestow, another badge.
@allcontributors add @AkshayCHD for bug fixing. 
Thanks for your contributions!
